name: GitHub Metrics
on:
  push:
  schedule: [{cron: "0 0 * * *"}] # 每天自動執行
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 輸出檔名
          filename: metrics.svg

          # 權杖
          token: ${{ secrets.METRICS_TOKEN }}

          # === 基本 GitHub 個人資料顯示 ===
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei
          config_twemoji: yes
          config_display: columns
          config_order: base, languages, anilist, achievements

          # === 程式語言相關 ===
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 1%

          # === 追蹤狀態（活躍程度） ===
          plugin_followup: yes
          plugin_lines: yes

          # === GitHub 成就展示 ===
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 10

          # === Anime 顯示（Anilist） ===
          plugin_anilist: yes
          plugin_anilist_user: TinyYana
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 6
          plugin_anilist_limit_characters: 12
          plugin_anilist_shuffle: yes

          # === 額外美化參數 ===
          template: classic
          config_padding: 8%
